version: "3.5"

volumes:
  kong_data: {}

networks:
  kong-net:

services:
  kong:
    #image: luizalabs/kong-user-standing:latest
    container_name: rate-limit-custom
    build:
      context: ./
    networks:
      - kong-net
    volumes:
      - ./kong.yml:/tmp/kong-declarative-config.yml
      - ./kong/plugins/rate-limit-custom:/usr/local/lib/luarocks/rocks-5.1/rate-limit-custom/1.0.0-1/lua/kong/plugins/rate-limit-custom
      - ./kong/plugins/rate-limit-custom:/usr/local/share/lua/5.1/kong/plugins/rate-limit-custom
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong-declarative-config.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled,rate-limit-custom
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
